### ISSUE TITLE
it seems I found a bug

### ISSUE THREAD

**Issue by jnereus** [tinyantstudio/EnhancedScrollView#3]
When I drag the card a very small distance on center left card ,the card change to the center but the changed  center card is not become grey

**Comment by jnereus** [comment]
` private void LerpTweenToTarget(float originValue, float targetValue, bool needTween = false)
    {
        if (!needTween)
        {
            SortEnhanceItem();
            originHorizontalValue = targetValue;
            UpdateEnhanceScrollView(targetValue);
            this.OnTweenOver();
        }
        else
        {
            originHorizontalValue = originValue;
            curHorizontalValue = targetValue;
            mCurrentDuration = 0.0f;
            //Add this it seems ok.   this.OnTweenOver();
        }
        enableLerpTween = needTween;
    }`

**Comment by jnereus** [comment]
` private void LerpTweenToTarget(float originValue, float targetValue, bool needTween = false)
    {
        if (!needTween)
        {
            SortEnhanceItem();
            originHorizontalValue = targetValue;
            UpdateEnhanceScrollView(targetValue);
            this.OnTweenOver();
        }
        else
        {
            originHorizontalValue = originValue;
            curHorizontalValue = targetValue;
            mCurrentDuration = 0.0f;
            //add this it seems everything ok.  this.OnTweenOver();
        }
        enableLerpTween = needTween;
    }
`

**Comment by LucasWeiF** [comment]
> When I drag the card a very small distance on center left card ,the card change to the center but the changed center card is not become grey

Yes,I have met the same question as you too.So I want to know if you have solved the problem.If that's all right ,I hope to get your help.

**Comment by AmethS** [comment]
> `private void LerpTweenToTarget(float originValue, float targetValue, bool needTween = false) { if (!needTween) { SortEnhanceItem(); originHorizontalValue = targetValue; UpdateEnhanceScrollView(targetValue); this.OnTweenOver(); } else { originHorizontalValue = originValue; curHorizontalValue = targetValue; mCurrentDuration = 0.0f; //add this it seems everything ok. this.OnTweenOver(); } enableLerpTween = needTween; }`

It works !  thank you bro~
